version: '3.8'

services:
  crm_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./logs:/app/logs 